title: Respirador Hacker
description: Iniciativa colaborativa para prototipagem de um modelo de respirador alternativo visando auxiliar o sistema de saúde em uma possível sobrecarga devido à COVID-19.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
