lang: pt-BR
github:
    is_project_page: true
    owner_name: Respirador Hacker
    owner_url: https://github.com/RespiradorHacker
title: Respirador Hacker
description: Modelo open-source de respirador alternativo visando auxiliar o sistema de saúde em uma possível sobrecarga devido à COVID-19.
google_analytics:
theme: jekyll-theme-cayman
